### ISSUE TITLE
does not write in the logging graph when the turtle file is too long

### ISSUE THREAD

**Issue by cdias** [globocom/simple-virtuoso-migrate#1]
This error ocorred when I submited a baseline turtle to create a new graph. The virtuoso-migrate executed and created the graph sucessfully but It  gives an error when it tries to write the history log and so, does not insert anything in the history graph:

Starting Virtuoso migration...
- Current version is: None
- Destination version is: migrate-1.0

Starting Migration!
===== executing =====
[ERROR] 
isql: **\* The statement has grown too long on lines 958 - 972.
Already 245745 bytes read without encountering a semicolon or ampersand
in the end of line! Goodbye!

**Comment by icaromedeiros** [comment]
Maybe is the SSH/iSQL connection or some kind of request-limit. Camila, do you know if the Virtuoso can mantain the connection open for a longer time? This should be parametrizable.

**Comment by wandenberg** [comment]
Fix applied. Please install latest version from master branch and check if is everything ok.

**Comment by romulojales** [comment]
Em quarta-feira, 20 de março de 2013, Wandenberg Peixoto escreveu:

> Fix applied. Please install latest version from master branch and check if
> is everything ok.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/globocom/simple-virtuoso-migrate/issues/1#issuecomment-15216104
> .

## 

Rômulo de Barros Correia Jales
Engenheiro da Computação
www.romulojales.com
