### ISSUE TITLE
Upgrade rdflib-sparqlstore to 0.2

### ISSUE THREAD

**Issue by romulojales** [globocom/simple-virtuoso-migrate#5]
The maintainer of rdflib-sparqlstore removed the 0.1 tag from pypi repositories and github.

The actual version, 0.2, breaks project's tests and example.

**Comment by wandenberg** [comment]
In fact the version 0.1 was never released on pypi, it was used from our internal repository.
Anyway, now is working with the version 0.2 and soon we will release a new version of the project on pypi too.

Thanks for the report.
